AWSTemplateFormatVersion: '2010-09-09'
Description: Application Load Balancer and Target Groups for Todo App

Parameters:
  Environment:
    Type: String
    Default: dev
    Description: Environment name (dev, staging, prod)
    AllowedValues:
      - dev
      - staging
      - prod

  AppName:
    Type: String
    Default: todo-app
    Description: Application name
    AllowedPattern: "^[a-z0-9-]+$"
    ConstraintDescription: Must contain only lowercase letters, numbers, and hyphens

  BackendPort:
    Type: Number
    Default: 4000
    Description: Backend API port number
    MinValue: 1024
    MaxValue: 65535

  FrontendPort:
    Type: Number
    Default: 3000
    Description: Frontend port number
    MinValue: 1024
    MaxValue: 65535

  BackendHealthCheckPath:
    Type: String
    Default: /api/health
    Description: Backend health check endpoint path

  FrontendHealthCheckPath:
    Type: String
    Default: /
    Description: Frontend health check endpoint path

  HealthCheckInterval:
    Type: Number
    Default: 30
    Description: Health check interval in seconds
    MinValue: 5
    MaxValue: 300

  HealthCheckTimeout:
    Type: Number
    Default: 5
    Description: Health check timeout in seconds
    MinValue: 2
    MaxValue: 120

  HealthyThresholdCount:
    Type: Number
    Default: 2
    Description: Number of consecutive successful health checks
    MinValue: 2
    MaxValue: 10

  UnhealthyThresholdCount:
    Type: Number
    Default: 3
    Description: Number of consecutive failed health checks
    MinValue: 2
    MaxValue: 10

  DeregistrationDelay:
    Type: Number
    Default: 30
    Description: Deregistration delay in seconds
    MinValue: 0
    MaxValue: 3600

Resources:
  # Application Load Balancer
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub '${Environment}-${AppName}-alb'
      Type: application
      Scheme: internet-facing
      IpAddressType: ipv4
      Subnets:
        - Fn::ImportValue: !Sub '${Environment}-shared-public-subnet-1-id'
        - Fn::ImportValue: !Sub '${Environment}-shared-public-subnet-2-id'
      SecurityGroups:
        - Fn::ImportValue: !Sub '${Environment}-${AppName}-alb-sg-id'
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-${AppName}-alb'
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: !Ref AppName

  # Backend Target Group
  BackendTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub '${Environment}-${AppName}-backend-tg'
      Port: !Ref BackendPort
      Protocol: HTTP
      VpcId:
        Fn::ImportValue: !Sub '${Environment}-shared-vpc-id'
      TargetType: ip
      HealthCheckEnabled: true
      HealthCheckProtocol: HTTP
      HealthCheckPath: !Ref BackendHealthCheckPath
      HealthCheckPort: traffic-port
      HealthCheckIntervalSeconds: !Ref HealthCheckInterval
      HealthCheckTimeoutSeconds: !Ref HealthCheckTimeout
      HealthyThresholdCount: !Ref HealthyThresholdCount
      UnhealthyThresholdCount: !Ref UnhealthyThresholdCount
      Matcher:
        HttpCode: '200'
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: !Ref DeregistrationDelay
        - Key: stickiness.enabled
          Value: 'false'
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-${AppName}-backend-tg'
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: !Ref AppName

  # Frontend Target Group
  FrontendTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub '${Environment}-${AppName}-frontend-tg'
      Port: !Ref FrontendPort
      Protocol: HTTP
      VpcId:
        Fn::ImportValue: !Sub '${Environment}-shared-vpc-id'
      TargetType: ip
      HealthCheckEnabled: true
      HealthCheckProtocol: HTTP
      HealthCheckPath: !Ref FrontendHealthCheckPath
      HealthCheckPort: traffic-port
      HealthCheckIntervalSeconds: !Ref HealthCheckInterval
      HealthCheckTimeoutSeconds: !Ref HealthCheckTimeout
      HealthyThresholdCount: !Ref HealthyThresholdCount
      UnhealthyThresholdCount: !Ref UnhealthyThresholdCount
      Matcher:
        HttpCode: '200'
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: !Ref DeregistrationDelay
        - Key: stickiness.enabled
          Value: 'false'
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-${AppName}-frontend-tg'
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: !Ref AppName

  # HTTP Listener (Port 80) - Default to Frontend
  HTTPListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref FrontendTargetGroup

  # Listener Rule for Backend API
  BackendListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref HTTPListener
      Priority: 1
      Conditions:
        - Field: path-pattern
          Values:
            - /api/*
      Actions:
        - Type: forward
          TargetGroupArn: !Ref BackendTargetGroup

Outputs:
  LoadBalancerArn:
    Description: ARN of the Application Load Balancer
    Value: !Ref ApplicationLoadBalancer
    Export:
      Name: !Sub '${Environment}-${AppName}-alb-arn'

  LoadBalancerDNS:
    Description: DNS name of the Application Load Balancer
    Value: !GetAtt ApplicationLoadBalancer.DNSName
    Export:
      Name: !Sub '${Environment}-${AppName}-alb-dns'

  LoadBalancerFullName:
    Description: Full name of the Application Load Balancer
    Value: !GetAtt ApplicationLoadBalancer.LoadBalancerFullName
    Export:
      Name: !Sub '${Environment}-${AppName}-alb-full-name'

  LoadBalancerHostedZoneId:
    Description: Canonical hosted zone ID of the load balancer
    Value: !GetAtt ApplicationLoadBalancer.CanonicalHostedZoneID
    Export:
      Name: !Sub '${Environment}-${AppName}-alb-hosted-zone-id'

  BackendTargetGroupArn:
    Description: ARN of the Backend Target Group
    Value: !Ref BackendTargetGroup
    Export:
      Name: !Sub '${Environment}-${AppName}-backend-tg-arn'

  FrontendTargetGroupArn:
    Description: ARN of the Frontend Target Group
    Value: !Ref FrontendTargetGroup
    Export:
      Name: !Sub '${Environment}-${AppName}-frontend-tg-arn'

  LoadBalancerURL:
    Description: URL of the Application Load Balancer
    Value: !Sub 'http://${ApplicationLoadBalancer.DNSName}'
    Export:
      Name: !Sub '${Environment}-${AppName}-alb-url'

